(load "interpreter.rkt")

(define tests
  (lambda ()
    (if (and (eq? (interpret "tests/test01.txt") 150)
             (eq? (interpret "tests/test02.txt") -4)
             (eq? (interpret "tests/test03.txt") 10)
             (eq? (interpret "tests/test04.txt") 16)
             (eq? (interpret "tests/test05.txt") 220)
             (eq? (interpret "tests/test06.txt") 5)
             (eq? (interpret "tests/test07.txt") 6)
             (eq? (interpret "tests/test08.txt") 10)
             (eq? (interpret "tests/test09.txt") 5)
             (eq? (interpret "tests/test10.txt") -39)
             (eq? (interpret "tests/test15.txt") 'true)
             (eq? (interpret "tests/test16.txt") '100)
             (eq? (interpret "tests/test17.txt") 'false)
             (eq? (interpret "tests/test18.txt") 'true)
             (eq? (interpret "tests/test19.txt") 128))
        #t
        #f)))